/* AUTOGENERATED FILE - MATCHING YOUR SCREENSHOTS */

import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () =>
  createClient(
    Deno.env.get("SUPABASE_URL"),
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
  );

// --- MAIN FUNCTION: Sends Form Data to 'clients' Table ---
export const set = async (
  key: string,
  value: any,
): Promise<void> => {
  const supabase = client();

  // 1. CLEANUP: Filter out fields that cause errors
  const {
    id, // REMOVE: Let Supabase generate the UUID
    type, // REMOVE: Not in your table
    submittedAt, // REMOVE: Prevents column mismatch
    createdAt, // REMOVE: Prevents "Column not found" error (Your DB uses 'created_at')
    ...dataToSave // KEEP: fullName, email, phone, package, domain, businessType, websitePackage, message
  } = value;

  // 2. INSERT: Send the cleaned data directly to the 'clients' table
  const { error } = await supabase
    .from("clients")
    .insert(dataToSave);

  if (error) {
    console.error("Supabase Insert Error:", error.message);
    throw new Error(error.message);
  }
};

// --- SUPPORT FUNCTIONS (Kept to prevent Plugin Crashes) ---
export const get = async (key: string): Promise<any> => {
  return null;
};
export const del = async (key: string): Promise<void> => {
  return;
};
export const mget = async (keys: string[]): Promise<any[]> => {
  return [];
};
export const mdel = async (keys: string[]): Promise<void> => {
  return;
};
export const getByPrefix = async (
  prefix: string,
): Promise<any[]> => {
  return [];
};

export const mset = async (
  keys: string[],
  values: any[],
): Promise<void> => {
  const supabase = client();
  const cleanValues = values.map((v) => {
    // Apply the same cleanup to bulk inserts
    const { id, type, submittedAt, createdAt, ...rest } = v;
    return rest;
  });
  const { error } = await supabase
    .from("clients")
    .insert(cleanValues);
  if (error) throw new Error(error.message);
};